name: Bug Report
description: File a bug report
labels: ["bug"]

body: 
  - type: textarea
    id: expected-result
    attributes:
      label: What happened? What did you expect to happen?
      description: What did you expect?
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: What did you do to make this happened? List the steps
      description: Reproduction Steps
    validations:
      required: true

  - type: textarea
    id: images
    attributes:
      label: If possible can you provide some images?
      description: Images goes here
    validations:
      required: false
        
  - type: textarea
    id: sys-info
    attributes: 
      label: Add your information here
      description: Add all the information
      value: >
      perating System: (MacOS/Windows/Linux (if linux specify distro)
        WPILIB info:
        ```
        Control + Shift + P > WPILIB: Open Project Information
        Open project information and paste it here 
        ```
    validations:
      required: true
      
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I've search for duplicated
          required: true
        - label: I have shown the entire traceback, if possible.
          required: true
        - label: I have provided all information about this bug.
          required: true
          
  - type: textarea
    id: additional-context
    attributes:
      label: If there is something you like to add or say please add it here
      description: Add here
    validations:
      required: false
